import { z } from 'zod';
import { EntityType, Instant, OpaqueId } from './enums.js';
import { CONTRACTS_VERSION } from './version.js';

/**
 * The verified command receipt (spec sections 8 and 13). Receipts are never deleted; undo is a
 * separate compensating command with its own receipt.
 */

export const CommandOutcome = z.enum([
  /** The change committed. */
  'committed',
  /** An observation merged into an existing record (e.g. duplicate wear report) and committed. */
  'merged',
  /** Validation failed; nothing was written. */
  'rejected',
  /** An edit's expected versions were stale; nothing was written. */
  'conflict',
]);
export type CommandOutcome = z.infer<typeof CommandOutcome>;

export const AffectedEntity = z.object({
  entityType: EntityType,
  entityId: z.string(),
  version: z.number().int().nonnegative(),
  /** Present for derived rows whose change is part of the verified result. */
  change: z.enum(['created', 'updated', 'retracted']).optional(),
});
export type AffectedEntity = z.infer<typeof AffectedEntity>;

export const EffectKind = z.enum(['board_revalidation', 'calendar_projection', 'search_index', 'media_job', 'notification']);
export type EffectKind = z.infer<typeof EffectKind>;

export const EffectStatus = z.enum(['pending', 'dispatched', 'projected', 'failed', 'superseded']);

export const CommandEffect = z.object({
  effectId: OpaqueId,
  kind: EffectKind,
  /** External effects leave Garderobe (Calendar, notifications); internal ones do not. */
  external: z.boolean(),
  status: EffectStatus,
  operationKey: z.string(),
});
export type CommandEffect = z.infer<typeof CommandEffect>;

/**
 * External-effect state of a receipt:
 * - none: the command has no external effect
 * - projection_pending: committed in D1; an external projection (e.g. Calendar) is still pending
 * - projected: every external effect has been verified by read-back
 * - failed: an external projection failed and remains visible for retry
 */
export const ExternalEffectState = z.enum(['none', 'projection_pending', 'projected', 'failed']);

export const ReceiptError = z.object({
  code: z.string(),
  message: z.string(),
  details: z.record(z.string(), z.unknown()).optional(),
});
export type ReceiptError = z.infer<typeof ReceiptError>;

export const CommandReceipt = z.object({
  schemaVersion: z.literal(CONTRACTS_VERSION),
  commandId: OpaqueId,
  idempotencyKey: z.string(),
  commandType: z.string(),
  outcome: CommandOutcome,
  /** True when this response is the stored receipt of an earlier identical request. */
  replayed: z.boolean(),
  /** True when an observation was accepted after internally rebasing stale expected versions. */
  rebased: z.boolean(),
  affected: z.array(AffectedEntity),
  /** Concise summary generated by trusted code from the committed state, never by a model. */
  summary: z.string(),
  /** Structured verified facts (e.g. counted wear, batch contents) for clients to render. */
  facts: z.record(z.string(), z.unknown()),
  effects: z.object({ state: ExternalEffectState, items: z.array(CommandEffect) }),
  undo: z.object({ available: z.boolean(), reason: z.string().optional() }),
  compensatesCommandId: OpaqueId.nullable(),
  undoneByCommandId: OpaqueId.nullable(),
  occurredAt: Instant,
  recordedAt: Instant,
  error: ReceiptError.nullable(),
});
export type CommandReceipt = z.infer<typeof CommandReceipt>;
