/**
 * Shared helpers of the local run mode (`npm run dev`, `npm run dev:token`, `npm run smoke:mcp`).
 *
 * Local sign-in: there is no Cloudflare Access in front of a local Worker, so the local run mode has
 * its own signing key. `setup` writes the PUBLIC key into .dev.vars as ACCESS_JWKS_JSON (accepted by
 * the Worker only when ENVIRONMENT is local or test) and keeps the private key in the git-ignored
 * .wrangler/ directory. Tokens made here are verified by the Worker's ordinary assertion check.
 * None of this exists in a deployment, and no Cloudflare credential is involved anywhere.
 */
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SignJWT, exportJWK, generateKeyPair, importJWK } from "jose";

export const WORKER_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const REPO_ROOT = path.resolve(WORKER_DIR, "../..");
export const STATE_DIR = path.join(WORKER_DIR, ".wrangler", "garderobe-local");
export const STATE_FILE = path.join(STATE_DIR, "state.json");
export const DEV_VARS = path.join(WORKER_DIR, ".dev.vars");

export const LOCAL = {
  appOrigin: process.env.GARDEROBE_APP_ORIGIN ?? "http://localhost:8787",
  mcpOrigin: process.env.GARDEROBE_MCP_ORIGIN ?? "http://127.0.0.1:8787",
  issuer: "https://garderobe-local.cloudflareaccess.com",
  audience: "garderobe-local-audience",
};

export function readState() {
  if (!existsSync(STATE_FILE)) return null;
  return JSON.parse(readFileSync(STATE_FILE, "utf8"));
}

export function writeState(state) {
  mkdirSync(STATE_DIR, { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), { mode: 0o600 });
}

const secret = (bytes) => randomBytes(bytes).toString("base64");

/** Create the local signing key and secrets once; returns the state (creating .dev.vars when missing). */
export async function ensureLocalSecrets() {
  let state = readState();
  if (!state?.privateJwk) {
    const { publicKey, privateKey } = await generateKeyPair("RS256", { extractable: true, modulusLength: 2048 });
    const kid = `local-${randomBytes(4).toString("hex")}`;
    state = {
      ...(state ?? {}),
      privateJwk: { ...(await exportJWK(privateKey)), kid, alg: "RS256" },
      publicJwk: { ...(await exportJWK(publicKey)), kid, alg: "RS256", use: "sig" },
      secrets: { CREDENTIAL_KEY: secret(32), STATE_SIGNING_KEY: secret(48), MEDIA_SIGNING_KEY: secret(48) },
      identity: { subject: `local-owner-${randomBytes(6).toString("hex")}`, email: "owner@garderobe.local" },
    };
    writeState(state);
  }
  const lines = [
    "# Generated by `npm run dev` for LOCAL runs only. Never used by a deployment.",
    `CREDENTIAL_KEY=${state.secrets.CREDENTIAL_KEY}`,
    `STATE_SIGNING_KEY=${state.secrets.STATE_SIGNING_KEY}`,
    `MEDIA_SIGNING_KEY=${state.secrets.MEDIA_SIGNING_KEY}`,
    // Single quotes: dotenv keeps the JSON literally.
    `ACCESS_JWKS_JSON='${JSON.stringify({ keys: [state.publicJwk] })}'`,
    "",
  ];
  writeFileSync(DEV_VARS, lines.join("\n"), { mode: 0o600 });
  return state;
}

/** A local sign-in assertion for an identity (default: the local owner). Valid for one hour. */
export async function localAssertion(identity) {
  const state = readState();
  if (!state?.privateJwk) throw new Error("local run mode is not set up; run `npm run dev -- setup` in apps/worker first");
  const who = identity ?? state.identity;
  const key = await importJWK(state.privateJwk, "RS256");
  const now = Math.floor(Date.now() / 1000);
  return new SignJWT({ ...(who.email ? { email: who.email } : {}), type: "app" })
    .setProtectedHeader({ alg: "RS256", kid: state.privateJwk.kid })
    .setIssuer(LOCAL.issuer)
    .setAudience(LOCAL.audience)
    .setSubject(who.subject)
    .setIssuedAt(now)
    .setExpirationTime(now + 3600)
    .sign(key);
}

/** fetch against the local API as the signed-in local owner. */
export async function api(method, route, body, extraHeaders = {}) {
  const headers = { "Cf-Access-Jwt-Assertion": await localAssertion(), ...extraHeaders };
  if (body !== undefined) headers["Content-Type"] = "application/json";
  const response = await fetch(`${LOCAL.appOrigin}${route}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body), redirect: "manual" });
  const text = await response.text();
  let json = null;
  try {
    json = text ? JSON.parse(text) : null;
  } catch {
    /* not JSON */
  }
  return { status: response.status, ok: response.ok, json, text, headers: response.headers };
}

/** Claim the seeded account for the local owner identity when it has not been claimed yet. Idempotent. */
export async function ensureClaimed() {
  const me = await api("GET", "/v1/me");
  if (me.ok) return { claimed: false, me: me.json };
  if (me.status !== 403 || me.json?.error?.code !== "identity_not_linked") throw new Error(`the local Worker did not answer as expected: ${me.status} ${me.text.slice(0, 300)}`);
  const state = readState();
  if (!state?.invitationCode) throw new Error("no local invitation found; run `npm run dev -- setup` again");
  const claim = await api("POST", "/auth/claim", { invitationCode: state.invitationCode });
  if (!claim.ok) throw new Error(`claim failed: ${claim.status} ${claim.text.slice(0, 300)}`);
  // The recovery kit is shown once; keep it with the other local-only state.
  writeState({ ...state, recoveryKit: claim.json.issuedRecoveryKit, claimedAt: new Date().toISOString() });
  return { claimed: true, me: claim.json };
}
