import type { ConflictFinding } from "./conflicts.ts";
import type { InventoryImportPlan } from "./inventory.ts";
import { OWNER_PROFILE_SHA256, PROFILE_MEASUREMENTS, PROFILE_RULES, PROFILE_SIZE_EXPERIENCES } from "./profile.ts";

const cell = (s: string | null | undefined) => (s ?? "").replace(/\|/g, "/").replace(/\n/g, " ");

/** Deterministic Markdown report: every CSV line, its disposition and reason, plus the conflicts. */
export function renderImportReport(plan: InventoryImportPlan, conflicts: ConflictFinding[]): string {
  const t = plan.totals;
  const lines: string[] = [];
  lines.push("# Inventory import report");
  lines.push("");
  lines.push("Generated by `npm run import:report` from the supplied documents. Do not edit by hand; a test fails if this file is stale.");
  lines.push("");
  lines.push(`- Source: \`requirements/${plan.sourceName}\` (${plan.sourceBytes} bytes, SHA-256 \`${plan.sourceSha256}\`)`);
  lines.push(`- Profile: \`requirements/chris-wardrobe-profile.md\` (SHA-256 \`${OWNER_PROFILE_SHA256}\`), imported verbatim as the style document`);
  lines.push(`- Sheet title: ${plan.title ?? "(none)"}`);
  lines.push("");
  lines.push("## Row accounting");
  lines.push("");
  lines.push(`Every one of the ${t.physicalLines} lines in the file is accounted for.`);
  lines.push("");
  lines.push("| Disposition | Lines | Meaning |");
  lines.push("| --- | --- | --- |");
  lines.push(`| imported | ${t.imported} | The line created a garment |`);
  lines.push(`| merged | ${t.merged} | The line is a further interchangeable unit of a garment created by another line (explicit mapping below) |`);
  lines.push(`| held | ${t.held} | The line could not be interpreted without guessing and was not imported |`);
  lines.push(`| not a data row | ${t.notDataRows} | Title and column header |`);
  lines.push(`| **total** | **${t.physicalLines}** | ${t.dataRows} data rows became ${t.garments} garments holding ${t.units} units |`);
  lines.push("");
  lines.push("| Category | Source rows | Garments | Units |");
  lines.push("| --- | --- | --- | --- |");
  for (const [category, c] of Object.entries(t.byCategory).sort(([a], [b]) => a.localeCompare(b))) lines.push(`| ${category} | ${c.rows} | ${c.garments} | ${c.units} |`);
  lines.push("");
  lines.push(`Planning policy of the imported garments: ${Object.entries(t.byPlanningPolicy).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${v} ${k}`).join(", ")}.`);
  lines.push("");
  lines.push("What the import deliberately does not do: it creates no garment the sheet does not list, imports or invents no wear history, lifts no restriction, and does not treat the sheet's cleanliness as observed (all laundered stock starts as an estimate).");
  lines.push("");
  lines.push("## Profile-versus-inventory conflicts");
  lines.push("");
  for (const f of conflicts) {
    lines.push(`### ${f.id} (${f.severity.replace("_", " ")}): ${f.title}`);
    lines.push("");
    if (f.profileQuote) lines.push(`- Profile: "${f.profileQuote}"`);
    lines.push(`- Inventory: ${f.inventoryEvidence}`);
    if (f.sourceRows.length > 0) lines.push(`- CSV lines: ${f.sourceRows.join(", ")}`);
    lines.push(`- What the importer did: ${f.importerAction}`);
    lines.push("");
  }
  lines.push("## Import issues");
  lines.push("");
  if (plan.issues.length === 0) lines.push("None.");
  for (const i of plan.issues) lines.push(`- (${i.severity.replace("_", " ")}) ${i.detail}`);
  lines.push("");
  lines.push("## Profile import");
  lines.push("");
  lines.push(`The profile text is stored unchanged as style document version 1. ${PROFILE_RULES.length} machine rules, ${PROFILE_MEASUREMENTS.length} dated body facts, ${PROFILE_SIZE_EXPERIENCES.length} size experiences and one active restriction are derived from it; each profile-derived record quotes its passage verbatim.`);
  lines.push("");
  lines.push("| Rule key | Kind | Status | Origin | Profile passage (first words) |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const r of PROFILE_RULES) lines.push(`| \`${r.key}\` | ${r.kind} | ${r.status.replace("_", " ")} | ${r.origin}${r.section ? ` §${r.section}` : ""} | ${cell(r.quotes[0]?.slice(0, 70) ?? "(specification section 7 research rule; not in the profile)")} |`);
  lines.push("");
  lines.push("## Every line");
  lines.push("");
  lines.push("| Line | Disposition | Category | Item as written | Garment ID | Reason |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const r of plan.rows) {
    const raw = r.raw as Record<string, string>;
    lines.push(`| ${r.sourceRow} | ${r.disposition.replace(/_/g, " ")} | ${cell(raw.Category ?? "")} | ${cell(raw.Item ?? raw.text ?? "")} | ${r.garmentId ? `\`${r.garmentId}\`` : ""} | ${cell(r.reason)} |`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Machine-readable form of the same report. */
export function importReportJson(plan: InventoryImportPlan, conflicts: ConflictFinding[]): Record<string, unknown> {
  return {
    source: { name: plan.sourceName, sha256: plan.sourceSha256, bytes: plan.sourceBytes, title: plan.title },
    profileSha256: OWNER_PROFILE_SHA256,
    importRunId: plan.importRunId,
    totals: plan.totals,
    rows: plan.rows.map((r) => ({ line: r.sourceRow, disposition: r.disposition, garmentId: r.garmentId, garmentName: r.garmentName, reason: r.reason })),
    garments: plan.garments.map((g) => ({ garmentId: g.garmentId, name: g.payload.name, category: g.payload.category, quantity: g.payload.quantity, planningPolicy: g.payload.planningPolicy, sourceLines: g.sourceRows, status: g.statusText })),
    issues: plan.issues,
    conflicts,
  };
}
