/**
 * Operations Worker of the DEVELOPMENT deployment (never deployed anywhere else; the deploy tooling's
 * guard only accepts development names).
 *
 * It does three things, all against the same resources the product Worker uses:
 *  - seeds the database through the real importer and the ordinary command service, plus a labelled
 *    synthetic second owner;
 *  - runs platform probes (D1, R2, Queues, Workflows, AI Gateway, AI Search, Images, outbound fetch,
 *    research providers) and returns identifiers, statuses, timings and counts only;
 *  - serves the automation door's public key at the standard Access certificate path.
 *
 * Every `/ops/*` request needs the operations token (generated by the deploy tooling, kept in its local
 * state; this Worker holds only its SHA-256). It holds no Cloudflare management credential.
 */
import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";
import { generateText, tool } from "ai";
import { z } from "zod";
import { BULK_CORRECT_LIMIT, CommandService, all, createFoundationRegistry, createPrincipal, createUser, first, type Principal } from "@garderobe/domain";
import { importOwnerData } from "@garderobe/domain/import";
import { AiSearchIndex, McpHttpClient, PROFILE_SPECS, createGatewayModel, eraseSearchInstance, profileSpec, provisionSearchInstance } from "@garderobe/assistant";
import { createCloudflareImagesBackgroundRemover, createCloudflareImagesTranscoder, createDohResolver } from "@garderobe/media";
import { appFor } from "../../../apps/worker/src/app.ts";
import type { Env as ProductEnv } from "../../../apps/worker/src/env.ts";
import { createInvitation } from "../../../apps/worker/src/identity/service.ts";
import profileText from "../../../requirements/chris-wardrobe-profile.md";
import inventoryCsv from "../../../requirements/wardrobe_inventory_clean.csv";

interface Env extends ProductEnv {
  AUTO_JWKS_JSON: string;
  OPS_TOKEN_SHA256: string;
  REHEARSAL?: string;
  PRODUCT?: Fetcher;
  PROBE_WORKFLOW?: Workflow;
}

const SYNTHETIC_OWNER = "Synthetic second owner (deployment test, not a person)";
const BULK_WORD = "bulkprobe";
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });
const hex = (bytes: ArrayBuffer) => [...new Uint8Array(bytes)].map((b) => b.toString(16).padStart(2, "0")).join("");
const sha256 = async (text: string) => hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)));
const brief = (error: unknown) => String((error as Error)?.message ?? error).slice(0, 400);

/** Two-step workflow with a durable sleep between the steps: the instance must survive its own suspension. */
export class OpsProbeWorkflow extends WorkflowEntrypoint<Env, { probeId: string }> {
  override async run(event: WorkflowEvent<{ probeId: string }>, step: WorkflowStep) {
    const started = await step.do("record start", async () => ({ probeId: event.payload.probeId, at: Date.now() }));
    await step.sleep("suspend", "5 seconds");
    return step.do("finish", async () => ({ ...started, resumedAfterMs: Date.now() - started.at }));
  }
}

async function authorized(request: Request, env: Env): Promise<boolean> {
  const token = /^Bearer\s+(.+)$/i.exec(request.headers.get("Authorization") ?? "")?.[1];
  if (!token || !env.OPS_TOKEN_SHA256) return false;
  const [a, b] = [await sha256(token), env.OPS_TOKEN_SHA256];
  let diff = a.length ^ b.length;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ (b.charCodeAt(i) || 0);
  return diff === 0;
}

const importer = (userId: string) => createPrincipal({ userId, actor: "system", channel: "import", scopes: ["read", "write", "admin"], authRef: "deploy-ops" });
const system = (userId: string) => createPrincipal({ userId, actor: "system", channel: "system", scopes: ["read", "write", "admin"], authRef: "deploy-ops" });
/** The synthetic owner acting on its own labelled test garments (corrections accept only an owner's authorization). */
const tester = (userId: string) => createPrincipal({ userId, actor: "owner", channel: "test", scopes: ["read", "write"], authRef: "deploy-ops" });

const realOwner = (env: Env) => first<{ user_id: string }>(env.DB, "SELECT user_id FROM users WHERE is_synthetic = 0 ORDER BY created_at LIMIT 1");
const syntheticOwner = (env: Env) => first<{ user_id: string }>(env.DB, "SELECT user_id FROM users WHERE is_synthetic = 1 AND display_name = ? ORDER BY created_at LIMIT 1", SYNTHETIC_OWNER);

async function requireSynthetic(env: Env): Promise<string> {
  const row = await syntheticOwner(env);
  if (!row) throw new Error("the synthetic second owner does not exist yet; run the seed first");
  return row.user_id;
}

function syntheticGarment(n: number, label: string) {
  return { name: `${label} ${String(n).padStart(3, "0")} (synthetic, not real stock)`, category: "shirt", roles: ["top"], careChannel: "service", acquisition: "owned", quantity: 1, isSynthetic: true, source: { kind: "system", note: "synthetic deployment-test garment" } };
}

/**
 * Seed. Resumable and idempotent: the importer's commands carry deterministic keys, so a call that ran
 * out of its per-invocation budget is simply called again and continues after replaying what is stored.
 */
async function seed(env: Env, body: { invite?: string[] }) {
  const db = env.DB;
  const userId = (await realOwner(env))?.user_id ?? (await createUser(db, { displayName: "Chris", isSynthetic: false })).userId;
  const service = new CommandService({ db, registry: createFoundationRegistry() });
  const result = await importOwnerData(service, importer(userId), { profileText, inventoryCsv });

  const syntheticId = (await syntheticOwner(env))?.user_id ?? (await createUser(db, { displayName: SYNTHETIC_OWNER, isSynthetic: true })).userId;
  for (let n = 1; n <= 3; n++) {
    await service.execute(importer(syntheticId), { type: "garment.create", payload: syntheticGarment(n, "Synthetic shirt"), idempotencyKey: `deploy-synthetic-garment:${n}`, expectedVersions: {}, authorization: "data_import", source: { channel: "import" } } as never);
  }
  const invitations: Record<string, string> = {};
  for (const who of body.invite ?? []) {
    if (who !== "owner" && who !== "synthetic") continue;
    invitations[who] = (await createInvitation(db, env, { userId: who === "owner" ? userId : syntheticId })).invitationCode;
  }
  return {
    complete: true,
    owner: { userId, receipts: result.receipts, replayed: result.replayed, conflicts: result.conflicts.length, profileSha256: result.profile.contentSha256 },
    synthetic: { userId: syntheticId },
    // One-time codes: returned to the deploy tooling's local state only, never written to evidence.
    invitations,
  };
}

/** What the import left in the database, as counts and one digest, for comparison with the local import. */
async function reconcile(env: Env) {
  const db = env.DB;
  const owner = await realOwner(env);
  if (!owner) return { seeded: false };
  const u = owner.user_id;
  const n = async (sql: string, ...params: unknown[]) => (await first<{ n: number }>(db, sql, ...params))?.n ?? 0;
  const rows = await all<{ name: string; category: string; units: number }>(
    db,
    `SELECT g.name, g.category, COALESCE((SELECT SUM(b.quantity) FROM stock_balances b WHERE b.user_id = g.user_id AND b.garment_id = g.garment_id AND b.bucket <> 'gone'), 0) AS units
     FROM garments g WHERE g.user_id = ? AND g.is_synthetic = 0 AND g.merged_into IS NULL AND g.removed_reason IS NULL ORDER BY g.name, g.category`,
    u,
  );
  const profile = await first<{ content_sha256: string }>(db, "SELECT content_sha256 FROM style_documents WHERE user_id = ? ORDER BY rowid LIMIT 1", u).catch(() => null);
  return {
    seeded: true,
    garments: rows.length,
    units: rows.reduce((sum, r) => sum + Number(r.units), 0),
    inventoryDigest: await sha256(rows.map((r) => `${r.name}|${r.category}|${r.units}`).join("\n")),
    profileSha256: profile?.content_sha256 ?? null,
    currentRules: await n("SELECT COUNT(*) AS n FROM style_rules WHERE user_id = ? AND is_current = 1", u),
    measurements: await n("SELECT COUNT(*) AS n FROM measurements WHERE user_id = ? AND superseded_by IS NULL", u),
    activeRestrictions: await n("SELECT COUNT(*) AS n FROM restrictions WHERE user_id = ? AND status = 'active'", u),
    wearObservations: await n("SELECT COUNT(*) AS n FROM wear_observations WHERE user_id = ?", u),
    laundryBatches: await n("SELECT COUNT(*) AS n FROM laundry_batches WHERE user_id = ?", u),
    importCommands: await n("SELECT COUNT(*) AS n FROM commands WHERE user_id = ? AND idempotency_key LIKE 'import:%'", u),
    syntheticOwners: await n("SELECT COUNT(*) AS n FROM users WHERE is_synthetic = 1"),
    linkedIdentities: await n("SELECT COUNT(*) AS n FROM auth_identities WHERE unlinked_at IS NULL"),
  };
}

// An 8x8 two-colour PNG, so no image file is needed.
const TINY_PNG = Uint8Array.from(atob("iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAGklEQVR42mP4gAROaGjAEQMVJZA5yIqoKAEA65h9AeCDkyEAAAAASUVORK5CYII="), (c) => c.charCodeAt(0));

type Probe = (env: Env, body: Record<string, unknown>) => Promise<Record<string, unknown>>;

const probes: Record<string, Probe> = {
  /** Applied migrations, and whether a batch whose LAST statement fails leaves its earlier statements unapplied. */
  async d1(env) {
    const applied = await all<{ name: string }>(env.DB, "SELECT name FROM d1_migrations ORDER BY id").catch(() => []);
    const userId = await requireSynthetic(env);
    const before = await first<{ wardrobe_revision: number }>(env.DB, "SELECT wardrobe_revision FROM owner_state WHERE user_id = ?", userId);
    let lateFailure = "batch unexpectedly succeeded";
    try {
      await env.DB.batch([
        env.DB.prepare("UPDATE owner_state SET wardrobe_revision = wardrobe_revision + 1 WHERE user_id = ?").bind(userId),
        env.DB.prepare("INSERT INTO users (user_id, display_name, created_at) VALUES (?, 'duplicate key, must fail', ?)").bind(userId, new Date().toISOString()),
      ]);
    } catch {
      lateFailure = "rejected";
    }
    const after = await first<{ wardrobe_revision: number }>(env.DB, "SELECT wardrobe_revision FROM owner_state WHERE user_id = ?", userId);
    const ok = lateFailure === "rejected" && before?.wardrobe_revision === after?.wardrobe_revision;
    return { ok, migrations: applied.map((m) => m.name), lateStatementFailure: lateFailure, earlierStatementRolledBack: before?.wardrobe_revision === after?.wardrobe_revision };
  },

  /**
   * Checklist row S08-029 on this database: simultaneous commands on one synthetic garment. The same
   * command sent eight times at once must yield one stored command; eight different corrections made
   * against the same garment version must not leave partial rows or receipts without a command.
   */
  async concurrency(env) {
    const userId = await requireSynthetic(env);
    const app = appFor(env);
    const run = Date.now().toString(36);
    const created = await app.service.execute(importer(userId), { type: "garment.create", payload: syntheticGarment(900, "Concurrency probe shirt"), idempotencyKey: "deploy-concurrency-garment", expectedVersions: {}, authorization: "data_import", source: { channel: "import" } } as never);
    const garmentId = (created.affected as { kind: string; id: string }[]).find((a) => a.kind === "garment")!.id;
    const version = (await first<{ version: number }>(env.DB, "SELECT version FROM garments WHERE user_id = ? AND garment_id = ?", userId, garmentId))!.version;
    const correct = (key: string, condition: string, expected: Record<string, number>) =>
      app.service
        .execute(tester(userId), { type: "garment.correct", payload: { garmentId, changes: { condition }, source: { kind: "system", note: "deployment concurrency probe" } }, idempotencyKey: key, expectedVersions: expected, authorization: "owner_tap", source: { channel: "test" } } as never)
        .then((r) => ({ ok: true as const, commandId: r.commandId, replayed: r.replayed }))
        .catch((e) => ({ ok: false as const, code: String((e as { code?: string }).code ?? "error"), message: brief(e) }));
    const same = await Promise.all(Array.from({ length: 8 }, () => correct(`deploy-conc-same-${run}`, `probe ${run}`, {})));
    const sameIds = new Set(same.filter((r) => r.ok).map((r) => (r as { commandId: string }).commandId));
    const conflicting = await Promise.all(Array.from({ length: 8 }, (_, i) => correct(`deploy-conc-diff-${run}-${i}`, `probe ${run} writer ${i}`, { [`garment:${garmentId}`]: version + 1 })));
    const committed = conflicting.filter((r) => r.ok).length;
    const stored = await all<{ idempotency_key: string }>(env.DB, "SELECT idempotency_key FROM commands WHERE user_id = ? AND idempotency_key LIKE ?", userId, `deploy-conc-%-${run}%`);
    const final = await first<{ version: number; condition: string }>(env.DB, "SELECT version, condition FROM garments WHERE user_id = ? AND garment_id = ?", userId, garmentId);
    const refusals = [...new Set(conflicting.filter((r) => !r.ok).map((r) => (r as { code: string }).code))];
    // One stored command for the repeated key; of eight different writers that all name the same current
    // version exactly one commits; a stored command exists for exactly the receipts that were returned;
    // the version advanced once per commit.
    const ok = sameIds.size === 1 && committed === 1 && stored.length === 2 && final!.version === version + 2;
    return { ok, sameKey: { calls: 8, distinctCommands: sameIds.size, errors: same.filter((r) => !r.ok).length }, sameExpectedVersion: { calls: 8, committed, refusalCodes: refusals }, storedCommands: stored.length, versionBefore: version, versionAfter: final!.version };
  },

  /** Add up to `create` labelled synthetic garments for the bulk-correction measurement (resumable; stops at the cap). */
  async bulk_prepare(env, body) {
    const userId = await requireSynthetic(env);
    const app = appFor(env);
    const have = (await first<{ n: number }>(env.DB, "SELECT COUNT(*) AS n FROM garments WHERE user_id = ? AND name LIKE ? AND removed_reason IS NULL", userId, `${BULK_WORD}%`))!.n;
    const want = Math.min(Number(body.create ?? 20), BULK_CORRECT_LIMIT - have);
    for (let n = have + 1; n <= have + want; n++) {
      await app.service.execute(importer(userId), { type: "garment.create", payload: syntheticGarment(n, `${BULK_WORD} shirt`), idempotencyKey: `deploy-bulk-garment:${n}`, expectedVersions: {}, authorization: "data_import", source: { channel: "import" } } as never);
    }
    return { ok: true, garments: have + Math.max(want, 0), cap: BULK_CORRECT_LIMIT, complete: have + Math.max(want, 0) >= BULK_CORRECT_LIMIT };
  },

  /** One `garment.bulk_correct` over the full cap, in one invocation of this Worker, against this database. */
  async bulk_correct(env) {
    const userId = await requireSynthetic(env);
    const app = appFor(env);
    const run = Date.now().toString(36);
    const started = Date.now();
    const receipt = await app.service.execute(tester(userId), { type: "garment.bulk_correct", payload: { selector: { search: BULK_WORD }, changes: { condition: `bulk probe ${run}` }, expectedCount: BULK_CORRECT_LIMIT, source: { kind: "system", note: "deployment bulk-correction measurement" } }, idempotencyKey: `deploy-bulk-correct-${run}`, expectedVersions: {}, authorization: "owner_tap", source: { channel: "test" } } as never);
    const ms = Date.now() - started;
    const changed = (await first<{ n: number }>(env.DB, "SELECT COUNT(*) AS n FROM garments WHERE user_id = ? AND condition = ?", userId, `bulk probe ${run}`))!.n;
    return { ok: changed === BULK_CORRECT_LIMIT, garments: BULK_CORRECT_LIMIT, changed, commandMs: ms, outcome: receipt.outcome, commandId: receipt.commandId };
  },

  /** Write, read back and delete one small object in each private bucket. */
  async r2(env) {
    const out: Record<string, unknown> = {};
    let ok = true;
    for (const [name, bucket] of [["MEDIA_BUCKET", env.MEDIA_BUCKET], ["EXPORT_BUCKET", env.EXPORT_BUCKET]] as const) {
      if (!bucket) {
        out[name] = "not bound";
        ok = false;
        continue;
      }
      const key = `ops-probe/${crypto.randomUUID()}.txt`;
      await bucket.put(key, "deployment probe object", { httpMetadata: { contentType: "text/plain" } });
      const read = await (await bucket.get(key))?.text();
      await bucket.delete(key);
      const gone = (await bucket.head(key)) === null;
      out[name] = { roundTrip: read === "deployment probe object", deleted: gone };
      ok &&= read === "deployment probe object" && gone;
    }
    return { ok, ...out };
  },

  /** Put one message the media consumer does not recognise on the queue; the verification run watches the dead-letter queue. */
  async queue_send(env, body) {
    if (!env.MEDIA_QUEUE) return { ok: false, reason: "MEDIA_QUEUE is not bound" };
    const probeId = String(body.probeId ?? crypto.randomUUID());
    await env.MEDIA_QUEUE.send({ kind: "deployment_probe_not_a_media_job", probeId });
    return { ok: true, probeId };
  },

  async workflow_start(env) {
    if (!env.PROBE_WORKFLOW) return { ok: false, reason: "PROBE_WORKFLOW is not bound" };
    const probeId = `probe-${Date.now().toString(36)}`;
    const instance = await env.PROBE_WORKFLOW.create({ id: probeId, params: { probeId } });
    return { ok: true, instanceId: instance.id };
  },

  async workflow_status(env, body) {
    if (!env.PROBE_WORKFLOW) return { ok: false, reason: "PROBE_WORKFLOW is not bound" };
    const status = await (await env.PROBE_WORKFLOW.get(String(body.instanceId))).status();
    return { ok: status.status === "complete", status: status.status, output: status.output ?? null, error: status.error ?? null };
  },

  /**
   * One operation of one model profile through the product's own Gateway adapter on the AI binding: no
   * provider key, the named gateway. Returns what was observed; recording it is a separate step so the
   * deploy tooling can add the Gateway's own log entry as billing evidence first.
   */
  async gateway(env, body) {
    const spec = profileSpec(String(body.profileId));
    const operation = String(body.operation);
    if (!spec) return { ok: false, reason: "unknown profile" };
    if (!spec.gatewayRoute) return { ok: false, reason: spec.pendingReason ?? "no Gateway route" };
    const runId = `probe-${spec.profileId}-${operation}-${Date.now().toString(36)}`;
    const model = createGatewayModel(env as never, env.AI_GATEWAY_ID, spec, { runId, task: "deployment_probe", attempt: 1, environment: env.ENVIRONMENT });
    const image = { type: "image" as const, image: TINY_PNG, mediaType: "image/png" };
    const started = Date.now();
    const result = await generateText({
      model,
      maxOutputTokens: 64,
      abortSignal: AbortSignal.timeout(Math.min(spec.timeoutMs, 60_000)),
      ...(operation === "tools"
        ? { prompt: "Call the report tool with the word ready.", tools: { report: tool({ description: "Report a single word.", inputSchema: z.object({ word: z.string() }) }) } }
        : operation === "structured_output"
          ? { prompt: 'Return only this JSON object and nothing else: {"ready": true}' }
          : operation === "vision"
            ? { messages: [{ role: "user" as const, content: [{ type: "text" as const, text: "How many pixels wide is this image? Answer with a number only." }, image] }] }
            : { prompt: "Reply with the single word: ready" }),
    } as never);
    const text = String(result.text ?? "");
    let passed = text.trim().length > 0;
    if (operation === "tools") passed = (result.toolCalls ?? []).length > 0;
    if (operation === "structured_output") {
      try {
        passed = JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1)).ready === true;
      } catch {
        passed = false;
      }
    }
    // The billing source, when the provider surfaces the Gateway's metadata on the response.
    const meta = JSON.stringify({ providerMetadata: result.providerMetadata ?? null, headers: result.response?.headers ?? null });
    const keySource = /"keySource"\s*:\s*"([A-Za-z_]+)"/.exec(meta)?.[1] ?? null;
    return { ok: passed, profileId: spec.profileId, operation, route: spec.gatewayRoute, runId, ms: Date.now() - started, resolvedModel: result.response?.modelId ?? null, inputTokens: result.usage?.inputTokens ?? null, outputTokens: result.usage?.outputTokens ?? null, keySource, finishReason: result.finishReason ?? null };
  },

  /** Record a probe result with the product's own command, so the profile becomes selectable (or stays visibly unavailable). */
  async gateway_record(env, body) {
    const userId = await requireSynthetic(env);
    const app = appFor(env);
    const payload = { profileId: String(body.profileId), operation: String(body.operation), result: body.result, billing: body.billing, reason: body.reason ?? null, resolvedModel: body.resolvedModel ?? null, gatewayId: env.AI_GATEWAY_ID };
    const receipt = await app.service.execute(system(userId), { type: "inference.record_probe", payload, idempotencyKey: `deploy-probe:${payload.profileId}:${payload.operation}:${Date.now().toString(36)}`, expectedVersions: {}, authorization: "system_schedule", source: { channel: "system" } } as never);
    return { ok: true, summary: receipt.summary, commandId: receipt.commandId };
  },

  async gateway_profiles() {
    return { ok: true, profiles: PROFILE_SPECS.map((p) => ({ profileId: p.profileId, route: p.gatewayRoute, operations: p.supportedOperations, pendingReason: p.pendingReason })) };
  },

  /** Provision the synthetic owner's private instance through the namespace binding, index one labelled document, find it, remove it. */
  async ai_search(env, body) {
    if (!env.AI_SEARCH) return { ok: false, reason: "AI_SEARCH is not bound" };
    const userId = await requireSynthetic(env);
    const provisioned = await provisionSearchInstance(env.AI_SEARCH as never, env.ENVIRONMENT, userId, env.AI_GATEWAY_ID!);
    const index = new AiSearchIndex(env.AI_SEARCH as never, env.ENVIRONMENT, userId);
    const marker = `zephyrquartz${Date.now().toString(36)}`;
    const sourceId = `research_note:deploy-probe-${marker}`;
    const started = Date.now();
    const upsert = await index.upsert({ sourceId, sourceVersion: 1, kind: "research_note", occurredAt: new Date().toISOString(), entityId: null, body: `Synthetic deployment probe note. Marker word: ${marker}. This is not owner data.` });
    const indexMs = Date.now() - started;
    const hits = upsert.status === "searchable" ? await index.search(marker, { limit: 5 }) : [];
    const found = hits.some((h) => h.sourceId === sourceId);
    await index.remove(sourceId).catch(() => undefined);
    const erased = body.erase === true ? await eraseSearchInstance(env.AI_SEARCH as never, env.ENVIRONMENT, userId) : null;
    return { ok: upsert.status === "searchable" && found, instance: provisioned.instance, created: provisioned.created, upsert: upsert.status, detail: upsert.detail ?? null, indexMs, hits: hits.length, found, erased: erased?.deleted ?? null };
  },

  /** The media workstream's Images adapters on the real binding: PNG to bounded PNG, and foreground segmentation. */
  async images(env) {
    if (!env.IMAGES) return { ok: false, reason: "IMAGES is not bound" };
    const transcoded = await createCloudflareImagesTranscoder(env.IMAGES as never).toPng({ bytes: TINY_PNG, maxEdge: 64 } as never);
    const segmented = await createCloudflareImagesBackgroundRemover(env.IMAGES as never).remove({ bytes: TINY_PNG } as never);
    const isPng = (r: { ok: boolean; png?: Uint8Array }) => r.ok && r.png !== undefined && r.png[0] === 0x89 && r.png[1] === 0x50;
    return { ok: isPng(transcoded as never), transcode: transcoded.ok ? { bytes: (transcoded as { png: Uint8Array }).png.byteLength, png: isPng(transcoded as never) } : { reason: (transcoded as { reason: string }).reason }, segmentation: segmented.ok ? { bytes: (segmented as { png: Uint8Array }).png.byteLength, png: isPng(segmented as never) } : { reason: (segmented as { reason: string }).reason } };
  },

  /** Whether the runtime refuses private destinations, and whether the media resolver's DNS-over-HTTPS lookups answer. */
  async outbound(env) {
    const attempt = async (url: string) => {
      try {
        const r = await fetch(url, { signal: AbortSignal.timeout(5_000), redirect: "manual" });
        return `answered ${r.status}`;
      } catch (e) {
        return `refused: ${brief(e).slice(0, 120)}`;
      }
    };
    const privateTargets = { loopback: await attempt("http://127.0.0.1/"), privateRange: await attempt("http://10.0.0.1/"), linkLocalMetadata: await attempt("http://169.254.169.254/latest/meta-data/") };
    const resolver = createDohResolver();
    const publicHost = await resolver("example.com").then((a) => a.length, (e) => `failed: ${brief(e)}`);
    const blocked = Object.values(privateTargets).every((v) => v.startsWith("refused"));
    return { ok: blocked && typeof publicHost === "number" && publicHost > 0, privateTargets, dohAddressesForExampleCom: publicHost, environment: env.ENVIRONMENT };
  },

  /**
   * The assistant's own MCP client against the hosted search providers, without a credential: discovery
   * only (`tools/list`), with the protocol revision each provider accepted in the specification's setup
   * record. A provider that needs a key answers with its own refusal, which is recorded as it is.
   */
  async research_mcp() {
    const list = async (endpoint: string, protocolVersion: string, sessionBased: boolean) => {
      const client = new McpHttpClient({ endpoint, fetch: (input, init) => fetch(input, init), protocolVersion, sessionBased, timeoutMs: 20_000, maxCalls: 4 });
      const started = Date.now();
      try {
        const tools = await (client as unknown as { listTools(): Promise<{ name: string }[]> }).listTools();
        return { ok: true, protocolVersion, ms: Date.now() - started, tools: tools.map((t) => t.name).slice(0, 20) };
      } catch (e) {
        return { ok: false, protocolVersion, ms: Date.now() - started, code: String((e as { code?: string }).code ?? "error"), reason: brief(e) };
      }
    };
    const exa = await list("https://mcp.exa.ai/mcp", "2025-11-25", true);
    const tavily = await list("https://mcp.tavily.com/mcp", "2026-07-28", false);
    return { ok: exa.ok, exa, tavily, note: "discovery without a stored credential; a search call with the owner's Tavily key is not made here" };
  },
};

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/cdn-cgi/access/certs") return new Response(env.AUTO_JWKS_JSON, { headers: { "Content-Type": "application/json", "Cache-Control": "max-age=60" } });
    if (!url.pathname.startsWith("/ops/")) {
      // Local rehearsal only: this Worker stands in front of the product Worker in one local session.
      if (env.REHEARSAL === "1" && env.PRODUCT) return env.PRODUCT.fetch(request);
      return json({ error: "not_found" }, 404);
    }
    if (!(await authorized(request, env))) return json({ error: "unauthorized" }, 401);
    if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405);
    const body = ((await request.json().catch(() => ({}))) ?? {}) as Record<string, unknown>;
    const started = Date.now();
    try {
      if (url.pathname === "/ops/seed") return json({ ...(await seed(env, body as { invite?: string[] })), ms: Date.now() - started });
      if (url.pathname === "/ops/reconcile") return json({ ...(await reconcile(env)), ms: Date.now() - started });
      const probe = /^\/ops\/probe\/([a-z0-9_]+)$/.exec(url.pathname)?.[1];
      if (probe && probes[probe]) return json({ probe, ...(await probes[probe](env, body)), ms: Date.now() - started });
      return json({ error: "not_found" }, 404);
    } catch (error) {
      // A failure is a result: the caller records it. `resumable` tells the seed loop to call again.
      return json({ ok: false, complete: false, resumable: true, error: brief(error), code: (error as { code?: string }).code ?? null, ms: Date.now() - started }, 200);
    }
  },
} satisfies ExportedHandler<Env>;
