/**
 * Local Worker entry for the simulation's comparison run (`wrangler dev --local` with the config
 * generated by tests/simulation/scripts/setup-local.ts). It is the product entry
 * (backend/src/index.ts) wrapped by the simulation hook, exactly as the dev deployment's entry is.
 */
import product, { GarderobeAssistant as ProductAssistant } from '../../../backend/src/index.js';
import { simulationFetch, withSimulation, type SimEnv } from './sim-hook.js';

export { DailyServiceWorkflow } from '../../../backend/src/index.js';

export class GarderobeAssistant extends withSimulation(ProductAssistant) {}

export default {
  fetch(request: Request, env: SimEnv, ctx: ExecutionContext): Promise<Response> {
    return simulationFetch(request, env, ctx, (r) => product.fetch(r, env, ctx));
  },
  queue: product.queue,
} satisfies ExportedHandler<SimEnv>;
